ClientEvents.lang('en_us', event => {
  event.renameItem('electrodynamics:oremolybdenum', 'Dark Molybdenite Ore'),
  event.renameItem('electrodynamics:deepslateoremolybdenum', 'Deep Dark Molybdenite Ore'),
  event.renameBlock('electrodynamics:oremolybdenum', 'Dark Molybdenite Ore'),
  event.renameBlock('electrodynamics:deepslateoremolybdenum', 'Deep Dark Molybdenite Ore'),
  event.renameItem('electrodynamics:crystalmolybdenum', 'Dark Molybdenum Crystal'),
  event.renameItem('electrodynamics:impuredustmolybdenum', 'Impure Dark Molybdenum Dust'),
  event.renameItem('electrodynamics:dustmolybdenum', 'Dark Molybdenum Dust'),
  event.renameItem('electrodynamics:ingotmolybdenum', 'Dark Molybdenum Ingot'),
  event.renameItem('alexscaves:uranium_shard', 'Crystalline Uranium Shard'),
  event.renameItem('alexscaves:uranium', 'Crystalline Uranium'),
  event.renameItem('alexscaves:block_of_uranium', 'Block of Crystalline Uranium'),
  event.renameBlock('alexscaves:block_of_uranium', 'Block of Crystalline Uranium'),
  event.renameItem('meadow:limestone', 'Alpstone'),
  event.renameItem('meadow:limestone_stairs', 'Alpstone Stairs'),
  event.renameItem('meadow:limestone_slab', 'Alpstone Slab'),
  event.renameItem('meadow:limestone_wall', 'Alpstone Wall'),
  event.renameItem('meadow:cobbled_limestone', 'Cobbled Alpstone'),
  event.renameItem('meadow:cobbled_limestone_stairs', 'Cobbled Alpstone Stairs'),
  event.renameItem('meadow:cobbled_limestone_slab', 'Cobbled Alpstone Slab'),
  event.renameItem('meadow:cobbled_limestone_wall', 'Cobbled Alpstone Wall'),
  event.renameItem('meadow:limestone_bricks', 'Alpstone Bricks'),
  event.renameItem('meadow:limestone_brick_stairs', 'Alpstone Brick Stairs'),
  event.renameItem('meadow:limestone_brick_slab', 'Alpstone Brick Slab'),
  event.renameItem('meadow:limestone_brick_wall', 'Alpstone Brick Wall'),
  event.renameItem('meadow:mossy_cobbled_limestone', 'Mossy Cobbled Alpstone'),
  event.renameItem('meadow:mossy_cobbled_limestone_stairs', 'Mossy Cobbled Alpstone Stairs'),
  event.renameItem('meadow:mossy_cobbled_limestone_slab', 'Mossy Cobbled Alpstone Slab'),
  event.renameItem('meadow:mossy_cobbled_limestone_wall', 'Mossy Cobbled Alpstone Wall'),
  event.renameItem('meadow:mossy_limestone_bricks', 'Mossy Alpstone Bricks'),
  event.renameItem('meadow:mossy_limestone_brick_stairs', 'Mossy Alpstone Brick Stairs'),
  event.renameItem('meadow:mossy_limestone_brick_slab', 'Mossy Alpstone Brick Slab'),
  event.renameItem('meadow:mossy_limestone_brick_wall', 'Mossy Alpstone Brick Wall'),
  event.renameItem('meadow:chiseled_limestone_bricks', 'Chiseled Alpstone Bricks'),
  event.renameItem('meadow:cracked_limestone_bricks', 'Cracked Alpstone Bricks'),
  event.renameItem('meadow:polished_limestone_bricks', 'Polished Alpstone'),
  event.renameItem('meadow:delphinium', 'Alpine Delphinium'),
  event.renameItem('meadow:pine_sapling', 'Fir Sapling'),
  event.renameItem('meadow:pine_leaves', 'Fir Leaves'),
  event.renameItem('meadow:pine_log', 'Fir Log'),
  event.renameItem('meadow:pine_wood', 'Fir Wood'),
  event.renameItem('meadow:stripped_pine_log', 'Stripped Fir Log'),
  event.renameItem('meadow:stripped_pine_wood', 'Stripped Fir Wood'),
  event.renameItem('meadow:pine_beam', 'Fir Beam'),
  event.renameItem('meadow:pine_planks', 'Fir Planks'),
  event.renameItem('meadow:pine_stairs', 'Fir Stairs'),
  event.renameItem('meadow:pine_slab', 'Fir Slab'),
  event.renameItem('meadow:pine_pressure_plate', 'Fir Pressure Plate'),
  event.renameItem('meadow:pine_trapdoor', 'Fir Trapdoor'),
  event.renameItem('meadow:pine_door', 'Fir Door'),
  event.renameItem('meadow:pine_barn_trapdoor', 'Fir Barn Trapdoor'),
  event.renameItem('meadow:pine_barn_door', 'Fir Barn Door'),
  event.renameItem('meadow:pine_fence', 'Fir Fence'),
  event.renameItem('meadow:pine_fence_gate', 'Fir Fence Gate'),
  event.renameItem('meadow:pine_railing', 'Fir Railing'),
  event.renameItem('meadow:shelf', 'Fir Shelf'),
  event.renameItem('meadow:chair', 'Fir Chair'),
  event.renameItem('meadow:table', 'Fir Table'),
  event.renameItem('meadow:bench', 'Fir Bench'),
  event.renameItem('meadow:pine_window', 'Fir Window'),
  event.renameItem('meadow:pine_sign', 'Fir Sign'),
  event.renameItem('meadow:pine_hanging_sign', 'Fir Hanging Sign'),
  event.renameItem('meadow:pine_button', 'Fir Button'),
  event.renameBlock('meadow:limestone', 'Alpstone'),
  event.renameBlock('meadow:limestone_stairs', 'Alpstone Stairs'),
  event.renameBlock('meadow:limestone_slab', 'Alpstone Slab'),
  event.renameBlock('meadow:limestone_wall', 'Alpstone Wall'),
  event.renameBlock('meadow:cobbled_limestone', 'Cobbled Alpstone'),
  event.renameBlock('meadow:cobbled_limestone_stairs', 'Cobbled Alpstone Stairs'),
  event.renameBlock('meadow:cobbled_limestone_slab', 'Cobbled Alpstone Slab'),
  event.renameBlock('meadow:cobbled_limestone_wall', 'Cobbled Alpstone Wall'),
  event.renameBlock('meadow:limestone_bricks', 'Alpstone Bricks'),
  event.renameBlock('meadow:limestone_brick_stairs', 'Alpstone Brick Stairs'),
  event.renameBlock('meadow:limestone_brick_slab', 'Alpstone Brick Slab'),
  event.renameBlock('meadow:limestone_brick_wall', 'Alpstone Brick Wall'),
  event.renameBlock('meadow:mossy_cobbled_limestone', 'Mossy Cobbled Alpstone'),
  event.renameBlock('meadow:mossy_cobbled_limestone_stairs', 'Mossy Cobbled Alpstone Stairs'),
  event.renameBlock('meadow:mossy_cobbled_limestone_slab', 'Mossy Cobbled Alpstone Slab'),
  event.renameBlock('meadow:mossy_cobbled_limestone_wall', 'Mossy Cobbled Alpstone Wall'),
  event.renameBlock('meadow:mossy_limestone_bricks', 'Mossy Alpstone Bricks'),
  event.renameBlock('meadow:mossy_limestone_brick_stairs', 'Mossy Alpstone Brick Stairs'),
  event.renameBlock('meadow:mossy_limestone_brick_slab', 'Mossy Alpstone Brick Slab'),
  event.renameBlock('meadow:mossy_limestone_brick_wall', 'Mossy Alpstone Brick Wall'),
  event.renameBlock('meadow:chiseled_limestone_bricks', 'Chiseled Alpstone Bricks'),
  event.renameBlock('meadow:cracked_limestone_bricks', 'Cracked Alpstone Bricks'),
  event.renameBlock('meadow:polished_limestone_bricks', 'Polished Alpstone'),
  event.renameBlock('meadow:delphinium', 'Alpine Delphinium'),
  event.renameBlock('meadow:pine_sapling', 'Fir Sapling'),
  event.renameBlock('meadow:pine_leaves', 'Fir Leaves'),
  event.renameBlock('meadow:pine_log', 'Fir Log'),
  event.renameBlock('meadow:pine_wood', 'Fir Wood'),
  event.renameBlock('meadow:stripped_pine_log', 'Stripped Fir Log'),
  event.renameBlock('meadow:stripped_pine_wood', 'Stripped Fir Wood'),
  event.renameBlock('meadow:pine_beam', 'Fir Beam'),
  event.renameBlock('meadow:pine_planks', 'Fir Planks'),
  event.renameBlock('meadow:pine_stairs', 'Fir Stairs'),
  event.renameBlock('meadow:pine_slab', 'Fir Slab'),
  event.renameBlock('meadow:pine_pressure_plate', 'Fir Pressure Plate'),
  event.renameBlock('meadow:pine_trapdoor', 'Fir Trapdoor'),
  event.renameBlock('meadow:pine_door', 'Fir Door'),
  event.renameBlock('meadow:pine_barn_trapdoor', 'Fir Barn Trapdoor'),
  event.renameBlock('meadow:pine_barn_door', 'Fir Barn Door'),
  event.renameBlock('meadow:pine_fence', 'Fir Fence'),
  event.renameBlock('meadow:pine_fence_gate', 'Fir Fence Gate'),
  event.renameBlock('meadow:pine_railing', 'Fir Railing'),
  event.renameBlock('meadow:shelf', 'Fir Shelf'),
  event.renameBlock('meadow:chair', 'Fir Chair'),
  event.renameBlock('meadow:table', 'Fir Table'),
  event.renameBlock('meadow:bench', 'Fir Bench'),
  event.renameBlock('meadow:pine_window', 'Fir Window'),
  event.renameBlock('meadow:pine_sign', 'Fir Sign'),
  event.renameBlock('meadow:pine_hanging_sign', 'Fir Hanging Sign'),
  event.renameBlock('meadow:pine_button', 'Fir Button'),
  event.renameItem('meadow:pine_boat', 'Fir Boat'),
  event.renameItem('meadow:pine_chest_boat', 'Fir Chest Boat'),
  event.renameEntity('meadow:pine_boat', 'Fir Boat'),
  event.renameEntity('meadow:pine_chest_boat', 'Fir Chest Boat')
})
